"""change config version to text

Revision ID: 0be7251f0f20
Revises: 9d67ecc13eb8
Create Date: 2020-09-13 11:29:02.204686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0be7251f0f20'
down_revision = '9d67ecc13eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexnet', sa.Column('config_ver', sa.Text(), nullable=True))
    op.drop_column('complexnet', 'config_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexnet', sa.Column('config_version', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('complexnet', 'config_ver')
    # ### end Alembic commands ###
