"""netconfig change

Revision ID: 0f45033728f1
Revises: f20e1146190a
Create Date: 2020-09-13 11:12:49.854821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f45033728f1'
down_revision = 'f20e1146190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netconfig', sa.Column('option_index', sa.Integer(), nullable=True))
    op.add_column('netconfig', sa.Column('system_index', sa.Integer(), nullable=True))
    op.drop_column('netconfig', 'self_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netconfig', sa.Column('self_index', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('netconfig', 'system_index')
    op.drop_column('netconfig', 'option_index')
    # ### end Alembic commands ###
