"""move priority to runstatus table

Revision ID: 22feb7727701
Revises: 484a233bef91
Create Date: 2020-11-23 15:28:55.031804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22feb7727701'
down_revision = '484a233bef91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runmission', 'priority')
    op.add_column('runmissionstatus', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runmissionstatus', 'priority')
    op.add_column('runmission', sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
