"""changes in gen tables

Revision ID: 263ef8dd486c
Revises: 3ccd8e2943df
Create Date: 2020-11-24 10:13:40.729304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263ef8dd486c'
down_revision = '3ccd8e2943df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generatemissionstatus', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generatemissionstatus', 'priority')
    # ### end Alembic commands ###
