"""changes in gen tables

Revision ID: 3ccd8e2943df
Revises: 22feb7727701
Create Date: 2020-11-24 09:38:46.043612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ccd8e2943df'
down_revision = '22feb7727701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generatemissionstatus', sa.Column('generate_mission_id', sa.Integer(), nullable=True))
    op.add_column('generatemissionstatus', sa.Column('run_mission_id', sa.Integer(), nullable=True))
    op.drop_constraint('generatemissionstatus_ibfk_1', 'generatemissionstatus', type_='foreignkey')
    op.create_foreign_key(None, 'generatemissionstatus', 'generatemission', ['generate_mission_id'], ['id'])
    op.drop_column('generatemissionstatus', 'generate_id')
    op.drop_column('generatemissionstatus', 'generate_mission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generatemissionstatus', sa.Column('generate_mission', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('generatemissionstatus', sa.Column('generate_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generatemissionstatus', type_='foreignkey')
    op.create_foreign_key('generatemissionstatus_ibfk_1', 'generatemissionstatus', 'generatemission', ['generate_mission'], ['id'])
    op.drop_column('generatemissionstatus', 'run_mission_id')
    op.drop_column('generatemissionstatus', 'generate_mission_id')
    # ### end Alembic commands ###
