"""change generate and run tables

Revision ID: 484a233bef91
Revises: b5451a96772f
Create Date: 2020-11-23 15:20:28.074455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '484a233bef91'
down_revision = 'b5451a96772f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generatemission', 'is_generate_subfolders')
    op.drop_column('generatemission', 'source_scenario')
    op.drop_column('generatemission', 'ext_events_folder')
    op.add_column('generatemissionstatus', sa.Column('ext_events_folder', sa.Text(), nullable=True))
    op.add_column('generatemissionstatus', sa.Column('is_generate_subfolders', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generatemissionstatus', 'is_generate_subfolders')
    op.drop_column('generatemissionstatus', 'ext_events_folder')
    op.add_column('generatemission', sa.Column('ext_events_folder', mysql.TEXT(), nullable=True))
    op.add_column('generatemission', sa.Column('source_scenario', mysql.TEXT(), nullable=True))
    op.add_column('generatemission', sa.Column('is_generate_subfolders', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
