"""changes in gen tables

Revision ID: 5d374ebb436c
Revises: 263ef8dd486c
Create Date: 2020-11-24 10:35:01.662884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d374ebb436c'
down_revision = '263ef8dd486c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generatestage', sa.Column('generate_mission_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generatestage', 'generate_mission_id')
    # ### end Alembic commands ###
