"""added columns to site

Revision ID: 68df9d7aae57
Revises: 94c591770daf
Create Date: 2020-09-16 21:03:52.218418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68df9d7aae57'
down_revision = '94c591770daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('auto_dir', sa.Text(), nullable=True))
    op.add_column('site', sa.Column('ext_scenario_filer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'ext_scenario_filer')
    op.drop_column('site', 'auto_dir')
    # ### end Alembic commands ###
