"""added generate stage table

Revision ID: 6dc4325a123c
Revises: 
Create Date: 2020-11-22 21:23:09.200142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc4325a123c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generatestage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generate_status_id', sa.Integer(), nullable=True),
    sa.Column('succedded', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('stage_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generatestage')
    # ### end Alembic commands ###
