"""added run and generate tables

Revision ID: 9199ea92d847
Revises: 
Create Date: 2020-11-18 15:36:26.411734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9199ea92d847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generatemission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_scenario', sa.Text(), nullable=True),
    sa.Column('ext_events_folder', sa.Text(), nullable=True),
    sa.Column('is_generate_subfolders', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generatemissionstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('generate_id', sa.Integer(), nullable=True),
    sa.Column('is_validated', sa.Integer(), nullable=True),
    sa.Column('is_in_db', sa.Integer(), nullable=True),
    sa.Column('is_generated', sa.Integer(), nullable=True),
    sa.Column('delete_after', sa.Boolean(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('generate_mission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generate_mission'], ['generatemission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('runmissionstatus', sa.Column('generate_mission', sa.Integer(), nullable=True))
    op.add_column('runmissionstatus', sa.Column('run_id', sa.Integer(), nullable=True))
    op.drop_column('runmissionstatus', 'is_validated')
    op.drop_column('runmissionstatus', 'is_generated')
    op.drop_column('runmissionstatus', 'is_db_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runmissionstatus', sa.Column('is_db_updated', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('runmissionstatus', sa.Column('is_generated', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('runmissionstatus', sa.Column('is_validated', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('runmissionstatus', 'run_id')
    op.drop_column('runmissionstatus', 'generate_mission')
    op.drop_table('generatemissionstatus')
    op.drop_table('generatemission')
    # ### end Alembic commands ###
