"""change site columns names

Revision ID: 94c591770daf
Revises: a095f2e52f2c
Create Date: 2020-09-16 12:16:57.697487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94c591770daf'
down_revision = 'a095f2e52f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('execrsice_conn', sa.Text(), nullable=True))
    op.add_column('site', sa.Column('execrsice_db', sa.Text(), nullable=True))
    op.add_column('site', sa.Column('octopus_conn', sa.Text(), nullable=True))
    op.add_column('site', sa.Column('octopus_db', sa.Text(), nullable=True))
    op.add_column('site', sa.Column('recording_db', sa.Text(), nullable=True))
    op.add_column('site', sa.Column('site_conn', sa.Text(), nullable=True))
    op.drop_column('site', 'execrsice_site_ip')
    op.drop_column('site', 'auto_data_site_ip')
    op.drop_column('site', 'auto_data_db_ip')
    op.drop_column('site', 'recording_db_ip')
    op.drop_column('site', 'execrsice_db_ip')
    op.drop_column('site', 'site_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('site_ip', mysql.TEXT(), nullable=True))
    op.add_column('site', sa.Column('execrsice_db_ip', mysql.TEXT(), nullable=True))
    op.add_column('site', sa.Column('recording_db_ip', mysql.TEXT(), nullable=True))
    op.add_column('site', sa.Column('auto_data_db_ip', mysql.TEXT(), nullable=True))
    op.add_column('site', sa.Column('auto_data_site_ip', mysql.TEXT(), nullable=True))
    op.add_column('site', sa.Column('execrsice_site_ip', mysql.TEXT(), nullable=True))
    op.drop_column('site', 'site_conn')
    op.drop_column('site', 'recording_db')
    op.drop_column('site', 'octopus_db')
    op.drop_column('site', 'octopus_conn')
    op.drop_column('site', 'execrsice_db')
    op.drop_column('site', 'execrsice_conn')
    # ### end Alembic commands ###
