"""stage type key

Revision ID: 9765efbf919c
Revises: 
Create Date: 2020-11-25 09:38:21.323475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9765efbf919c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'generatestatistics', 'generatemissionstatus', ['generate_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generatestatistics', type_='foreignkey')
    # ### end Alembic commands ###
