"""netconfig change2

Revision ID: 9d67ecc13eb8
Revises: 0f45033728f1
Create Date: 2020-09-13 11:15:30.000044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d67ecc13eb8'
down_revision = '0f45033728f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netconfig', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netconfig', sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
