"""update version for complex net

Revision ID: a095f2e52f2c
Revises: ca7dc068ab02
Create Date: 2020-09-16 08:49:20.199623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a095f2e52f2c'
down_revision = 'ca7dc068ab02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('netsystem')
    op.add_column('complexnet', sa.Column('changed_by', sa.Integer(), nullable=True))
    op.add_column('complexnet', sa.Column('config_version', sa.Text(), nullable=True))
    op.drop_column('complexnet', 'Project_id')
    op.add_column('complexnet', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('netconfig', sa.Column('comp_index', sa.Integer(), nullable=True))
    op.add_column('netconfig', sa.Column('complex_net', sa.Integer(), nullable=True))
    op.add_column('netconfig', sa.Column('element_index', sa.Integer(), nullable=True))
    op.add_column('netconfig', sa.Column('option_index', sa.Integer(), nullable=True))
    op.add_column('netconfig', sa.Column('system_index', sa.Integer(), nullable=True))
    op.drop_constraint('netconfig_ibfk_1', 'netconfig', type_='foreignkey')
    op.create_foreign_key(None, 'netconfig', 'complexnet', ['complex_net'], ['id'])
    op.drop_column('netconfig', 'Backup_Env')
    op.drop_column('netconfig', 'Link_Ext_Simulation')
    op.drop_column('netconfig', 'Smiulation_Watch')
    op.drop_column('netconfig', 'Backup_Env_Ext_Flag')
    op.drop_column('netconfig', 'Simulation_Dis')
    op.drop_column('netconfig', 'Complex_Net_ID')
    op.drop_column('netconfig', 'Lnk_System')
    op.drop_column('netconfig', 'Simulation_Ext_Flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netconfig', sa.Column('Simulation_Ext_Flag', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('netconfig', sa.Column('Lnk_System', mysql.TEXT(), nullable=True))
    op.add_column('netconfig', sa.Column('Complex_Net_ID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('netconfig', sa.Column('Simulation_Dis', mysql.TEXT(), nullable=True))
    op.add_column('netconfig', sa.Column('Backup_Env_Ext_Flag', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('netconfig', sa.Column('Smiulation_Watch', mysql.TEXT(), nullable=True))
    op.add_column('netconfig', sa.Column('Link_Ext_Simulation', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('netconfig', sa.Column('Backup_Env', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'netconfig', type_='foreignkey')
    op.create_foreign_key('netconfig_ibfk_1', 'netconfig', 'complexnet', ['Complex_Net_ID'], ['id'])
    op.drop_column('netconfig', 'system_index')
    op.drop_column('netconfig', 'option_index')
    op.drop_column('netconfig', 'element_index')
    op.drop_column('netconfig', 'complex_net')
    op.drop_column('netconfig', 'comp_index')
    op.add_column('complexnet', sa.Column('Project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('complexnet', 'project_id')
    op.drop_column('complexnet', 'config_version')
    op.drop_column('complexnet', 'changed_by')
    op.create_table('netsystem',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('system_type', mysql.TEXT(), nullable=True),
    sa.Column('system_num', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kind', mysql.TEXT(), nullable=True),
    sa.Column('Complex_Net_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Complex_Net_ID'], ['complexnet.id'], name='netsystem_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
