"""added is_hidden and is_dbrf colomns to dbconnections table

Revision ID: a63a05e4d577
Revises: e70799f6977e
Create Date: 2020-08-20 07:33:44.249871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63a05e4d577'
down_revision = 'e70799f6977e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbconnections', sa.Column('is_dbrf', sa.Boolean(), nullable=True))
    op.add_column('dbconnections', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbconnections', 'is_hidden')
    op.drop_column('dbconnections', 'is_dbrf')
    # ### end Alembic commands ###
