"""add project id to run stage

Revision ID: bf16aa91a187
Revises: 68df9d7aae57
Create Date: 2020-09-22 12:08:56.740574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf16aa91a187'
down_revision = '68df9d7aae57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stagerunmani', sa.Column('changed_by', sa.Integer(), nullable=True))
    op.add_column('stagerunmani', sa.Column('project_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stagerunmani', 'project_id')
    op.drop_column('stagerunmani', 'changed_by')
    # ### end Alembic commands ###
