"""change config version to text2

Revision ID: ca7dc068ab02
Revises: 0be7251f0f20
Create Date: 2020-09-13 11:30:07.914906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca7dc068ab02'
down_revision = '0be7251f0f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexnet', sa.Column('config_version', sa.Text(), nullable=True))
    op.drop_column('complexnet', 'config_ver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexnet', sa.Column('config_ver', mysql.TEXT(), nullable=True))
    op.drop_column('complexnet', 'config_version')
    # ### end Alembic commands ###
