"""adding runmission and status

Revision ID: cdfe6cd95467
Revises: b36a31bae17e
Create Date: 2020-11-01 11:04:52.533397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfe6cd95467'
down_revision = 'b36a31bae17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runmissionstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('is_validated', sa.Integer(), nullable=True),
    sa.Column('is_db_updated', sa.Integer(), nullable=True),
    sa.Column('is_generated', sa.Integer(), nullable=True),
    sa.Column('delete_after', sa.Boolean(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('run_mission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_mission'], ['runmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runmissionstatus')
    op.drop_table('runmission')
    # ### end Alembic commands ###
