"""adding permission column

Revision ID: e70799f6977e
Revises: 
Create Date: 2020-08-18 11:23:14.575868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e70799f6977e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setupruns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('scenario_name', sa.Text(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setupsandruns',
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['setupruns.id'], ),
    sa.ForeignKeyConstraint(['setup_id'], ['analysesetup.id'], )
    )
    op.drop_table('overview')
    op.add_column('analyseresult', sa.Column('function_id', sa.Integer(), nullable=True))
    op.add_column('analyseresult', sa.Column('mission_id', sa.Integer(), nullable=True))
    op.add_column('analyseresult', sa.Column('run_status', sa.Integer(), nullable=True))
    op.add_column('analyseresult', sa.Column('scenario_name', sa.Text(), nullable=True))
    op.add_column('analysetask', sa.Column('run_status', sa.Integer(), nullable=True))
    op.add_column('analysetask', sa.Column('scenario_name', sa.Text(), nullable=True))
    op.add_column('analysetask', sa.Column('time_elapsed', sa.Float(), nullable=True))
    op.add_column('functionsgroup', sa.Column('permissions', sa.Integer(), nullable=True))
    op.add_column('mission', sa.Column('project', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission', 'project')
    op.drop_column('functionsgroup', 'permissions')
    op.drop_column('analysetask', 'time_elapsed')
    op.drop_column('analysetask', 'scenario_name')
    op.drop_column('analysetask', 'run_status')
    op.drop_column('analyseresult', 'scenario_name')
    op.drop_column('analyseresult', 'run_status')
    op.drop_column('analyseresult', 'mission_id')
    op.drop_column('analyseresult', 'function_id')
    op.create_table('overview',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mission_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('elapsed_time', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('setupsandruns')
    op.drop_table('setupruns')
    # ### end Alembic commands ###
